In [1]:
import pandas as pd

In [2]:
df_NaCl = pd.read_csv("../Data/Mutation_data/Current_AleDB_mut_call/GLU no_chemical.csv")

In [3]:
#Starting mutations

starting_df = pd.read_csv("../Data/Mutation_data/Current_AleDB_mut_call/TOL NaCl_mut.csv")
starting_mutation = starting_df[starting_df['TOL NaCl A1 F0 I1 R1']==1]

df_NaCl=df_NaCl.drop(index=df_NaCl[df_NaCl.Position.isin(starting_mutation.Position)].index)

In [4]:
#additional starting mutation

df_NaCl=df_NaCl.drop(index=df_NaCl[df_NaCl.Position=='1,979,486'].index)

In [5]:
end_point_samples=['BOP27-M9-NC_000913_3gb-log-37-Glucose2-NH4Cl1-KH2PO43-MgSO4024-O2 A3 F412 I1 R1',
                   'BOP27-M9-NC_000913_3gb-log-37-Glucose2-NH4Cl1-KH2PO43-MgSO4024-O2 A4 F403 I1 R1',
                   'BOP27-M9-NC_000913_3gb-log-37-Glucose2-NH4Cl1-KH2PO43-MgSO4024-O2 A5 F150 I1 R1',
                   'BOP27-M9-NC_000913_3gb-log-37-Glucose2-NH4Cl1-KH2PO43-MgSO4024-O2 A6 F406 I1 R1',
                   'BOP27-M9-NC_000913_3gb-log-37-Glucose2-NH4Cl1-KH2PO43-MgSO4024-O2 A7 F422 I51 R1',
                   'BOP27-M9-NC_000913_3gb-log-37-Glucose2-NH4Cl1-KH2PO43-MgSO4024-O2 A8 F380 I1 R1',
                   'BOP27-M9-NC_000913_3gb-log-37-Glucose2-NH4Cl1-KH2PO43-MgSO4024-O2 A9 F433 I1 R1',
                'BOP27-M9-NC_000913_3gb-log-37-Glucose2-NH4Cl1-KH2PO43-MgSO4024-O2 A10 F418 I1 R1',
                  ]

In [6]:
df_NaCl_end=df_NaCl[end_point_samples].fillna(0).astype('int64')
df_NaCl_end=df_NaCl_end.drop(index=df_NaCl_end[df_NaCl_end.sum(axis=1)==0].index)
df_NaCl_end.columns=df_NaCl_end.columns.str.replace("BOP27-M9-NC_000913_3gb-log-37-Glucose2-NH4Cl1-KH2PO43-MgSO4024-O2","GLU")

In [7]:
for i in df_NaCl_end.index:
    df_NaCl_end.loc[i,'Position']=df_NaCl.loc[i,'Position']
    df_NaCl_end.loc[i,'Mutation Type']=df_NaCl.loc[i,'Mutation Type']
    df_NaCl_end.loc[i,'Sequence Change']=df_NaCl.loc[i,'Sequence Change']
    df_NaCl_end.loc[i,'Gene']=df_NaCl.loc[i,'Gene']
    df_NaCl_end.loc[i,'Function']=df_NaCl.loc[i,'Function']
    df_NaCl_end.loc[i,'Product']=df_NaCl.loc[i,'Product']
    df_NaCl_end.loc[i,'GO Process']=df_NaCl.loc[i,'GO Process']
    df_NaCl_end.loc[i,'GO Component']=df_NaCl.loc[i,'GO Component']
    df_NaCl_end.loc[i,'Protein change']=df_NaCl.loc[i,'Details']

In [8]:
new_col = ['Position', 'Mutation Type', 'Sequence Change', 'Gene',
       'Function', 'Product', 'GO Process', 'GO Component', 'Protein change','GLU A3 F412 I1 R1', 'GLU A4 F403 I1 R1', 'GLU A5 F150 I1 R1',
       'GLU A6 F406 I1 R1', 'GLU A7 F422 I51 R1', 'GLU A8 F380 I1 R1',
       'GLU A9 F433 I1 R1', 'GLU A10 F418 I1 R1']

In [9]:
df_NaCl_end=df_NaCl_end[new_col].reset_index(drop=True)

In [10]:
df_NaCl_end.head()

,Position,Mutation Type,Sequence Change,Gene,Function,Product,GO Process,GO Component,Protein change,GLU A3 F412 I1 R1,GLU A4 F403 I1 R1,GLU A5 F150 I1 R1,GLU A6 F406 I1 R1,GLU A7 F422 I51 R1,GLU A8 F380 I1 R1,GLU A9 F433 I1 R1,GLU A10 F418 I1 R1
0,"1,869,873",SNP,T→G,yeaH,NaN,UPF0229 family protein,NaN,NaN,F307V (TTC→GTC),0,0,0,0,1,0,0,0
1,"3,815,859",DEL,Δ82 bp,"[rph],[rph]",NaN,"[rph],[rph]",NaN,NaN,NaN,1,1,1,1,1,1,1,1
2,"647,430",SNP,C→T,citG,NaN,2-(5''-triphosphoribosyl)-3'-dephosphocoenzyme...,NaN,NaN,R27H (CGC→CAC),0,0,0,0,0,1,0,0
3,"637,742",SNP,G→C,"ybdO, dsbG",NaN,putative DNA-binding transcriptional regulator...,NaN,NaN,intergenic (‑124/+85),0,0,0,1,0,0,0,0
4,"718,928",SNP,T→G,speF,NaN,"ornithine decarboxylase isozyme, inducible",NaN,NaN,E511D (GAA→GAC),0,0,0,1,0,0,0,0

In [11]:
dups_dir = "../../ALE_3strain_salt_growth/AMP_dup_run/glu/dups/"

In [12]:
import os

dir_content = os.listdir(dups_dir)
sample_list = []

for sub in dir_content:
    d = os.path.join(dups_dir,sub)
    if os.path.isdir(d)==True:
        sample_list.append(sub)

In [13]:
sample_list

['4-403-1-1',
 '8-380-1-1',
 '9-433-1-1',
 '6-406-1-1',
 '10-418-1-1',
 '7-422-51-1',
 '3-412-1-1',
 '5-150-1-1']

In [14]:
#Convert breseq directory names to column names used in Variant call files

col_names=pd.DataFrame(index=sample_list)
col_names['col_names']=col_names.index

col_names[['A','F','I','R']]=col_names['col_names'].str.split("-", expand=True)
col_names=col_names.sort_values(by="A")

for i in col_names.index:
    col_names.loc[i,'col_names']="GLU A"+col_names.loc[i,'A']+" F"+col_names.loc[i,'F']+" I"+col_names.loc[i,'I']+" R1"

In [15]:
col_names

                     col_names   A    F   I  R
10-418-1-1  GLU A10 F418 I1 R1  10  418   1  1
3-412-1-1    GLU A3 F412 I1 R1   3  412   1  1
4-403-1-1    GLU A4 F403 I1 R1   4  403   1  1
5-150-1-1    GLU A5 F150 I1 R1   5  150   1  1
6-406-1-1    GLU A6 F406 I1 R1   6  406   1  1
7-422-51-1  GLU A7 F422 I51 R1   7  422  51  1
8-380-1-1    GLU A8 F380 I1 R1   8  380   1  1
9-433-1-1    GLU A9 F433 I1 R1   9  433   1  1

In [16]:
for file in col_names.index:

    duplication_df_temp = pd.read_csv(dups_dir+file+"/"+file+"_genes.csv")
    
    if duplication_df_temp.index.size==0:
        continue
    
    k=0    
    for dup_count in duplication_df_temp.index:
        
        temp_row = pd.DataFrame()
        temp_row.loc[k,'Position'] = str(duplication_df_temp.loc[dup_count,'Start'])
        temp_row.loc[k,'Mutation Type'] = 'DUP'
        temp_row.loc[k,'Sequence Change'] = format (duplication_df_temp.loc[dup_count,'Width'], ',d')+" bp x"+str(duplication_df_temp.loc[dup_count,'Multiplicity'])
        temp_row.loc[k,'Gene']=duplication_df_temp.loc[dup_count,'Gene List'].replace("['","").replace("']","").replace("'","")
        temp_row.loc[k,'Protein change']="Duplication"
        temp_row.loc[k,col_names.loc[file,'col_names']]=1
        temp_row=temp_row.fillna("")
        df_NaCl_end=df_NaCl_end.append(temp_row)

In [17]:
df_NaCl_end['Position']=df_NaCl_end['Position'].str.replace(",","")

In [18]:
df_NaCl_end['Position']=df_NaCl_end['Position'].astype('int64')

In [19]:
df_NaCl_end=df_NaCl_end.sort_values(by="Position").reset_index(drop=True)

In [20]:
for i in df_NaCl_end.index:
    df_NaCl_end.loc[i,'Position']=format(int(df_NaCl_end.loc[i,'Position']),",")

In [21]:
df_NaCl_end[df_NaCl_end['Mutation Type']=="MOB"]

,Position,Mutation Type,Sequence Change,Gene,Function,Product,GO Process,GO Component,Protein change,GLU A3 F412 I1 R1,GLU A4 F403 I1 R1,GLU A5 F150 I1 R1,GLU A6 F406 I1 R1,GLU A7 F422 I51 R1,GLU A8 F380 I1 R1,GLU A9 F433 I1 R1,GLU A10 F418 I1 R1
8,"111,051",MOB,IS1 (–) +9 bp,mutT,NaN,dGTP-preferring nucleoside triphosphate pyroph...,NaN,NaN,coding (8‑16/390 nt),0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
87,"1,292,989",MOB,IS1 (+) +8 bp,"hns, tdk",NaN,global DNA-binding transcriptional dual regula...,NaN,NaN,intergenic (‑67/‑531),0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
88,"1,293,008",MOB,IS1 (+) +9 bp,"hns, tdk",NaN,global DNA-binding transcriptional dual regula...,NaN,NaN,intergenic (‑86/‑511),0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
89,"1,293,015",MOB,IS1 (–) +8 bp,"hns, tdk",NaN,global DNA-binding transcriptional dual regula...,NaN,NaN,intergenic (‑93/‑505),0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
90,"1,293,032",MOB,IS1 (–) +8 bp,"hns, tdk",NaN,global DNA-binding transcriptional dual regula...,NaN,NaN,intergenic (‑110/‑488),0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
91,"1,293,036",MOB,IS2 (+) +5 bp,"hns, tdk",NaN,global DNA-binding transcriptional dual regula...,NaN,NaN,intergenic (‑114/‑487),1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
112,"1,630,598",MOB,IS5 (+) +4 bp,ydfI,NaN,putative NAD-dependent D-mannonate oxidoreductase,NaN,NaN,coding (313‑316/1461 nt),0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
124,"1,879,829",MOB,Δ1 bp :: IS186 (+) +6 bp :: Δ1 bp,yeaR,NaN,"DUF1971 family protein, nitrate-inducible",NaN,NaN,coding (115‑120/360 nt),0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
129,"1,995,398",MOB,IS5 (–) +4 bp,"uvrY, yecF",NaN,response regulator in two-component regulatory...,NaN,NaN,intergenic (‑39/‑417),0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
149,"2,224,288",MOB,IS5 (+) +4 bp,pbpG,NaN,D-alanyl-D-alanine endopeptidase,NaN,NaN,coding (580‑583/933 nt),0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
162,"2,483,770",MOB,IS5 (–) +4 bp,evgA,NaN,response regulator in two-component regulatory...,NaN,NaN,coding (16‑19/615 nt),0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
182,"2,876,678",MOB,IS5 (+) +4 bp,iap,NaN,aminopeptidase in alkaline phosphatase isozyme...,NaN,NaN,coding (98‑101/1038 nt),0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
261,"3,968,900",MOB,IS5 (–) +4 bp,wecA,NaN,UDP-GlcNAc:undecaprenylphosphate GlcNAc-1-phos...,NaN,NaN,coding (985‑988/1104 nt),0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [22]:
df_NaCl_end.to_csv("../Data/Mutation_data/Variant_calls/no_chemical.csv")